server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      client:
        provider:
          auth0:
            issuer-uri: https://dev-lggipgkjxyl0wurk.us.auth0.com/
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email

      resourceserver:
        jwt:
          issuer-uri: https://dev-lggipgkjxyl0wurk.us.auth0.com/